#pragma once

#include <c10/core/Device.h>
// #include <c10/core/Layout.h>
#include <c10/core/MemoryFormat.h>
#include <c10/core/ScalarType.h>
// #include <c10/core/ScalarTypeToTypeMeta.h>
// #include <c10/core/Storage.h>
#include <c10/core/SymIntArrayRef.h>
// #include <c10/core/TensorImpl.h>
#include <c10/tensor_options.h>
// #include <c10/core/UndefinedTensorImpl.h>
// #include <c10/core/WrapDimMinimal.h>
// #include <c10/util/C++17.h>
// #include <c10/util/Exception.h>
// #include <c10/util/ExclusivelyOwned.h>
// #include <c10/util/ExclusivelyOwnedTensorTraits.h>
// #include <c10/util/MaybeOwned.h>
#include <optional>
// #include <c10/util/intrusive_ptr.h>

// #include <ATen/core/NamedTensor.h>
// #include <ATen/core/QuantizerBase.h>
// #include <ATen/core/TensorAccessor.h>
// #include <ATen/StorageUtils.h>

// namespace c10 {
// class Scalar;
// }

// namespace torch::autograd {

// struct Node;

// } // namespace torch::autograd

namespace at {

class Tensor;
class TensorBase;

class TensorBase {
//  public:
//   struct unsafe_borrow_t { explicit unsafe_borrow_t() = default; };

//  protected:
//   // Create a Tensor with a +0 reference count. Special care must be
//   // taken to avoid decrementing this reference count at destruction
//   // time. Intended to support MaybeOwnedTraits<Tensor>.
//   explicit TensorBase(unsafe_borrow_t, const TensorBase& rhs)
//       : impl_(c10::intrusive_ptr<at::TensorImpl, UndefinedTensorImpl>(rhs.impl_.get(), c10::raw::DontIncreaseRefcount{})) {}
//   friend MaybeOwnedTraits<TensorBase>;

 public:
  TensorBase() = default;
  // This constructor should not be used by end users and is an implementation
  // detail invoked by autogenerated code.
  // explicit TensorBase(
  //     c10::intrusive_ptr<TensorImpl, UndefinedTensorImpl> tensor_impl)
  //     : impl_(std::move(tensor_impl)) {
  //   if (impl_.get() == nullptr) {
  //     throw std::runtime_error("TensorImpl with nullptr is not supported");
  //   }
  // }
  TensorBase(const TensorBase&) = default;
  // TensorBase(TensorBase&&) noexcept = default;
  ~TensorBase() noexcept = default;
};

} // namespace at
